#
# Copyright (C) Patrik Jonell and contributors 2021.
# Licensed under the MIT license. See LICENSE.txt file in the project root for details.
#

version: '3'
services:
  webmushra:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - "8000:80"
    command: /start-reload.sh
    depends_on:
      - db
    environment:
      MONGO_USERNAME: db_user
      MONGO_PASSWORD: db_pass
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: db_user
      MONGO_INITDB_ROOT_PASSWORD: db_pass
